apiVersion: v1
kind: Service
metadata:
  name: vue-sample-ssr-node-port-service
spec:
  type: NodePort
  selector:
    component: vue-sample-ssr
  ports:
    - port: 5000
      targetPort: 8000
      nodePort: 32001
